site_name: Gofra
site_description: Documentation for Gofra programming language
site_author: Kirill Zhosul
site_url: https://gofralang.github.io/docs

theme:
  name: mkdocs
  language: en

repo_name: gofralang/docs
repo_url: https://github.com/gofralang/docs
edit_uri: edit/main/

nav:
  - About: index.md
  - Installation: installation.md
  - Tutorial: tutorial/index.md
  - Advanced: advanced/index.md
